from typing import Protocol
from frayerstore.models.course import Course
from frayerstore.models.course_create import CourseCreate


class CourseRepository(Protocol):
    def get_by_id(self, id: int) -> Course | None: ...
    def get_by_slug(self, slug: str) -> Course | None: ...
    def get_by_name(self, name: str) -> Course | None: ...
    def create(self, data: CourseCreate) -> Course: ...
